export const sagaActions = {
  FETCH_ALL_EMPLOYEES: "FETCH_ALL_EMPLOYEES",
  SEARCH_EMPLOYEES_BY_ID: "SEARCH_EMPLOYEES_BY_ID",
  UPDATE_RECORD: "UPDATE_RECORD",
  SAVE_RECORDS: "SAVE_RECORDS",
  DELETE_RECORD: "DELETE_RECORD",
};
